//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int ContID { get; set; }
        public string country_code { get; set; }
        public string country_enName { get; set; }
        public string country_arName { get; set; }
        public string country_enNationality { get; set; }
        public string country_arNationality { get; set; }
    }
}
