//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElTahiPostVideosRelation
    {
        public int ElTahiPostVideosRelationID { get; set; }
        public Nullable<int> ElTahiPostID { get; set; }
        public Nullable<int> ElTahiPostVideosID { get; set; }
        public Nullable<int> ElTahiVidRelationRegUserID { get; set; }
        public Nullable<System.DateTime> ElTahiVidRelationRegDT { get; set; }
    
        public virtual ElTahiPost ElTahiPost { get; set; }
    }
}
