//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElTahiCategory
    {
        public ElTahiCategory()
        {
            this.ELTahiTopUsers = new HashSet<ELTahiTopUser>();
        }
    
        public int ElTahiCategoryID { get; set; }
        public string ElTahiCategory1 { get; set; }
        public Nullable<System.DateTime> ElTahiCategoryRegDT { get; set; }
        public Nullable<int> ElTahiCategoryRegUserID { get; set; }
        public Nullable<int> ElTahiCategoryStatusID { get; set; }
        public Nullable<bool> ElTahiCategoryActivationFlag { get; set; }
    
        public virtual ElTahiAdmin ElTahiAdmin { get; set; }
        public virtual ElTahiStatu ElTahiStatu { get; set; }
        public virtual ICollection<ELTahiTopUser> ELTahiTopUsers { get; set; }
    }
}
