//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElTahiAdmin
    {
        public ElTahiAdmin()
        {
            this.ElTahiCategories = new HashSet<ElTahiCategory>();
            this.ElTahiStatus = new HashSet<ElTahiStatu>();
            this.ElTahiStatus1 = new HashSet<ElTahiStatu>();
            this.ElTahiTypes = new HashSet<ElTahiType>();
        }
    
        public int EltahiAdminID { get; set; }
        public string EltahiAdUserName { get; set; }
        public string EltahiAdUserPassWord { get; set; }
        public Nullable<System.DateTime> EltahiAdRegdateTime { get; set; }
        public Nullable<int> EltahiAdRoleID { get; set; }
        public Nullable<int> EltahiAdStatusID { get; set; }
    
        public virtual ElTahiRole ElTahiRole { get; set; }
        public virtual ICollection<ElTahiCategory> ElTahiCategories { get; set; }
        public virtual ICollection<ElTahiStatu> ElTahiStatus { get; set; }
        public virtual ICollection<ElTahiStatu> ElTahiStatus1 { get; set; }
        public virtual ICollection<ElTahiType> ElTahiTypes { get; set; }
    }
}
