//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElTahiRecipeRelation
    {
        public int TahiRecipeRelationID { get; set; }
        public Nullable<int> TahiRecipeParentID { get; set; }
        public Nullable<int> TahiRecipeChild { get; set; }
        public Nullable<int> TahiUserID { get; set; }
        public Nullable<System.DateTime> TahiRecipeRelationRegDT { get; set; }
    }
}
