//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElTahiSubRecipePostIngradient
    {
        public int ELTahiSubRecipPostID { get; set; }
        public Nullable<int> ElTahiRecipePostID { get; set; }
        public Nullable<int> ElTahiSubRecipePostID { get; set; }
        public Nullable<int> ElTahiPostingradientID { get; set; }
        public string ElTahiPostRecipIngrName { get; set; }
        public string ElTahiPostRecipWight { get; set; }
        public Nullable<int> ElTahiPostID { get; set; }
        public Nullable<int> ELTahiPostUserID { get; set; }
        public string ELTahiPostWightUnit { get; set; }
        public string ElTahSubResIngDetails { get; set; }
    }
}
