//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElTahiType
    {
        public ElTahiType()
        {
            this.ElTahiSuppliers = new HashSet<ElTahiSupplier>();
            this.ElTahiUsers = new HashSet<ElTahiUser>();
        }
    
        public int ElTahiTypesID { get; set; }
        public string ElTahiType1 { get; set; }
        public Nullable<System.DateTime> ElTahiTypeRegDT { get; set; }
        public Nullable<int> ElTahiTypeRegUserID { get; set; }
        public Nullable<int> ElTahiTypeStatusID { get; set; }
        public Nullable<bool> ElTahiTypeActivationFlag { get; set; }
    
        public virtual ElTahiAdmin ElTahiAdmin { get; set; }
        public virtual ICollection<ElTahiSupplier> ElTahiSuppliers { get; set; }
        public virtual ICollection<ElTahiUser> ElTahiUsers { get; set; }
    }
}
