//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELTahiJobPost
    {
        public int TahiJobPostID { get; set; }
        public Nullable<int> TahiJobUserID { get; set; }
        public string TahiJobTitle { get; set; }
        public string TahiJobComp { get; set; }
        public string TahiJobLocation { get; set; }
        public string TahiJobType { get; set; }
        public string TahiJobWorkplace { get; set; }
        public string TahiJobDescraption { get; set; }
        public Nullable<System.DateTime> TahiJobEndDate { get; set; }
        public Nullable<bool> TahiJobFlag { get; set; }
        public Nullable<System.DateTime> TahiJobRegesterDateT { get; set; }
        public Nullable<int> ElTahiPerantPostID { get; set; }
    }
}
