//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElTahiRecipePostMethod
    {
        public int ElTahiRecipePostMethodID { get; set; }
        public Nullable<int> ElTahiRecipePostID { get; set; }
        public Nullable<int> ElTahiRecipeTypeID { get; set; }
        public Nullable<int> ElTahiCookingMethodID { get; set; }
        public Nullable<int> ElTahiCuisineID { get; set; }
        public Nullable<int> ElTahiUserReg { get; set; }
        public Nullable<System.DateTime> ElTahiRMethodUpdateDt { get; set; }
    
        public virtual CookingMethod CookingMethod { get; set; }
        public virtual EltahiRecipeType EltahiRecipeType { get; set; }
        public virtual TahiCuisine TahiCuisine { get; set; }
    }
}
