//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElTahiPostComment
    {
        public int ELTahiPostCommentID { get; set; }
        public Nullable<int> ELTahiPerentPostID { get; set; }
        public string ElTahiComment { get; set; }
        public Nullable<int> ELTahiUserID { get; set; }
        public Nullable<System.DateTime> ELTahiComRegDT { get; set; }
    }
}
