//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElTahiSupplier
    {
        public ElTahiSupplier()
        {
            this.ELTahiTopSuppliers = new HashSet<ELTahiTopSupplier>();
        }
    
        public int ElTahiSupplierID { get; set; }
        public string ElTahiSupplierCompName { get; set; }
        public string ElTahiFirstName { get; set; }
        public string ELTahiSecondName { get; set; }
        public string ElTahiLastName { get; set; }
        public Nullable<System.DateTime> ElTahiSupplierBirthdate { get; set; }
        public string ElTahiSupplierEmail { get; set; }
        public string ElTahiSupplierMobile { get; set; }
        public Nullable<int> ElTahiSupplierTypeID { get; set; }
        public string ElTahiSupplierBio { get; set; }
        public Nullable<System.DateTime> ElTahiRegDateTime { get; set; }
        public Nullable<System.DateTime> ElTahiUpdateDT { get; set; }
        public Nullable<System.DateTime> ElTahiLastLoginDT { get; set; }
        public Nullable<int> ELTahiSupplierStatusID { get; set; }
        public string ELTahiSupplierName { get; set; }
        public string ElTahiSupplierPassWord { get; set; }
    
        public virtual ElTahiType ElTahiType { get; set; }
        public virtual ICollection<ELTahiTopSupplier> ELTahiTopSuppliers { get; set; }
    }
}
