//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElTahiProfileImage
    {
        public int ElTahiProfileImageID { get; set; }
        public string ElTahiProfileImageURL { get; set; }
        public string ElTahiProfileImageName { get; set; }
        public Nullable<int> ElTahiProfileImageUserID { get; set; }
        public Nullable<System.DateTime> UploadDateTime { get; set; }
    }
}
