//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElTahiSupRescipePost
    {
        public int ElTahiSubRecipePostID { get; set; }
        public Nullable<int> ElTahiRecipePostID { get; set; }
        public string ElTahiRecipePostHeader { get; set; }
        public string ElTahiRecipePostBody { get; set; }
        public Nullable<int> ElTahiRecipePostUserID { get; set; }
        public Nullable<int> ElTahiRecipePostStatusID { get; set; }
        public Nullable<System.DateTime> ELTahiRecipePostRegDT { get; set; }
        public Nullable<System.DateTime> ElTahiRecipePostUpdateDT { get; set; }
    }
}
