//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElTahiPostComponentRelation
    {
        public int ElTahiPostComponentRelationID { get; set; }
        public Nullable<int> ElTahiPostID { get; set; }
        public Nullable<int> ElTahiComponentID { get; set; }
        public Nullable<int> ElTahiPostComRelationUserID { get; set; }
        public Nullable<System.DateTime> ElTahiPostComRelationRegDT { get; set; }
    
        public virtual ElTahiPostComponent ElTahiPostComponent { get; set; }
        public virtual ElTahiPost ElTahiPost { get; set; }
        public virtual ElTahiUser ElTahiUser { get; set; }
    }
}
