//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElTahiPostImage
    {
        public ElTahiPostImage()
        {
            this.ElTahiPostImagesRelations = new HashSet<ElTahiPostImagesRelation>();
        }
    
        public int ElTahiPostImageID { get; set; }
        public string ElTahiPostImageURL { get; set; }
        public Nullable<int> ElTahiPostImageUserID { get; set; }
        public Nullable<int> ElTahiPostImageStatusID { get; set; }
        public Nullable<System.DateTime> ElTahiPostImageRegDT { get; set; }
    
        public virtual ElTahiStatu ElTahiStatu { get; set; }
        public virtual ElTahiUser ElTahiUser { get; set; }
        public virtual ICollection<ElTahiPostImagesRelation> ElTahiPostImagesRelations { get; set; }
    }
}
