//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElTahiRole
    {
        public ElTahiRole()
        {
            this.ElTahiAdmins = new HashSet<ElTahiAdmin>();
        }
    
        public int ElTahiRoleID { get; set; }
        public string ElTahiRole1 { get; set; }
        public string ElTahiRoleDesc { get; set; }
        public Nullable<int> ElTahiRoleUserID { get; set; }
        public Nullable<System.DateTime> ElTahiRegDT { get; set; }
        public Nullable<bool> RoleActivavtionFlag { get; set; }
    
        public virtual ICollection<ElTahiAdmin> ElTahiAdmins { get; set; }
    }
}
