//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELTahiPerantPost
    {
        public int ELTahiPostPerantID { get; set; }
        public Nullable<int> ElTahiPostUserID { get; set; }
        public Nullable<System.DateTime> ElTahiPostRegDT { get; set; }
        public Nullable<int> ELTahiPostType { get; set; }
    }
}
