//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElTahiStatu
    {
        public ElTahiStatu()
        {
            this.ElTahiCategories = new HashSet<ElTahiCategory>();
            this.ElTahiPostImages = new HashSet<ElTahiPostImage>();
            this.ElTahiPostVideos = new HashSet<ElTahiPostVideo>();
            this.ELTahiTopSuppliers = new HashSet<ELTahiTopSupplier>();
            this.ELTahiTopUsers = new HashSet<ELTahiTopUser>();
            this.ElTahiUsers = new HashSet<ElTahiUser>();
        }
    
        public int ElTahiStatusID { get; set; }
        public string ElTahiStatus { get; set; }
        public Nullable<int> ElTahiStatusRegAdminID { get; set; }
        public Nullable<System.DateTime> ElTahiStatusRegDT { get; set; }
        public Nullable<int> ElTahiStatusUpdateAdminID { get; set; }
        public Nullable<System.DateTime> ElTahiStatusUpdateDT { get; set; }
        public Nullable<bool> ActivationFlag { get; set; }
    
        public virtual ElTahiAdmin ElTahiAdmin { get; set; }
        public virtual ElTahiAdmin ElTahiAdmin1 { get; set; }
        public virtual ICollection<ElTahiCategory> ElTahiCategories { get; set; }
        public virtual ICollection<ElTahiPostImage> ElTahiPostImages { get; set; }
        public virtual ICollection<ElTahiPostVideo> ElTahiPostVideos { get; set; }
        public virtual ICollection<ELTahiTopSupplier> ELTahiTopSuppliers { get; set; }
        public virtual ICollection<ELTahiTopUser> ELTahiTopUsers { get; set; }
        public virtual ICollection<ElTahiUser> ElTahiUsers { get; set; }
    }
}
