//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElTahiOtherPost
    {
        public int ElTahiOtherPostsID { get; set; }
        public Nullable<int> ElTahiPostUser { get; set; }
        public Nullable<int> ElTahiPerantPostID { get; set; }
        public string ElTahiOtherPostTitle { get; set; }
        public string ElTahiotherPostDetail { get; set; }
        public string ElTahiOtherPostImageURL { get; set; }
        public string ElTahiOtherPostType { get; set; }
        public string ElTahiProvideAdvice { get; set; }
        public Nullable<System.DateTime> ElTahiOtherPostRegDT { get; set; }
    }
}
