//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELTahiMeasuringUnit
    {
        public int ElTahiMeasuringUnitID { get; set; }
        public string TahiMeasuringUnitSmall { get; set; }
        public string TahiMeasuringUnitCapital { get; set; }
        public Nullable<System.DateTime> TahiMeasuringUnitRegDT { get; set; }
    }
}
