//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElTahiPostImagesRelation
    {
        public int ElTahiPostImageRelationID { get; set; }
        public Nullable<int> ElTahiPostID { get; set; }
        public Nullable<int> ElTahiPostImageID { get; set; }
        public Nullable<int> ElTahiRelationRegUserID { get; set; }
        public Nullable<System.DateTime> ElTahiRelationRegDT { get; set; }
    
        public virtual ElTahiPostImage ElTahiPostImage { get; set; }
        public virtual ElTahiUser ElTahiUser { get; set; }
    }
}
