//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendship
    {
        public int ElTahiRequesterUserId { get; set; }
        public int ElTahiFriendUserId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    
        public virtual ElTahiUser ElTahiFriendUser { get; set; }
        public virtual ElTahiUser ElTahiRequestorUser { get; set; }
    }
}
