//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tahi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TahiSupInformation
    {
        public int tahiinfootherID { get; set; }
        public string tahiSupName { get; set; }
        public string tahisupPhone { get; set; }
        public string tahitagline { get; set; }
        public string tahiwebsiteurl { get; set; }
        public string tahisupdescription { get; set; }
        public string tahisupindustry { get; set; }
        public string tahisupcompsize { get; set; }
        public string tahicomptype { get; set; }
        public Nullable<System.DateTime> tahisupyearfounder { get; set; }
        public string tahisupSpecialities { get; set; }
        public string tahisupAddress { get; set; }
        public Nullable<int> tahiSupUserID { get; set; }
        public Nullable<System.DateTime> tahiSupInfoRegDT { get; set; }
        public Nullable<System.DateTime> TahiSupInfoUpdateDT { get; set; }
    }
}
